   INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('employee','$2a$10$ef4UbtkMA8tTUxkOGPe5EeAirs/ZgoldbkE7QJPddd80pA.JP7fTq',1);
   INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('manager','$2a$10$ef4UbtkMA8tTUxkOGPe5EeAirs/ZgoldbkE7QJPddd80pA.JP7fTq',1);

   INSERT INTO AUTHORITIES VALUES('employee','ROLE_EMPLOYEE');
   INSERT INTO AUTHORITIES VALUES('employee','ROLE_USER');
   INSERT INTO AUTHORITIES VALUES('manager','ROLE_MANAGER');
   INSERT INTO AUTHORITIES VALUES('manager','ROLE_USER');