 CREATE  DATABASE IF NOT EXISTS `user_db`;
 USE `user_db`;

 DROP  TABLE  IF EXISTS  `USERS`;

 CREATE TABLE `USERS`
   (
	USERNAME VARCHAR(50) NOT NULL,
        PASSWORD VARCHAR(68) NOT NULL,
        ENABLED TINYINT(1) NOT NULL,
        PRIMARY KEY(USERNAME)
   ) ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT  CHARSET=latin1;


   DROP TABLE IF EXISTS  `AUTHORITIES`;
   
   CREATE TABLE `AUTHORITIES`
   (
		USERNAME VARCHAR(50) NOT NULL,
        AUTHORITY VARCHAR(68) NOT NULL,
        FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
   ) ENGINE=InnoDb AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

